package jp.reikai.stats

/**
 * Generated by scripts/fork/ttu-statistics/make-fixture.mjs from ッツ Ebook Reader's own functions
 * (BSD-3-Clause, Copyright (c) 2026, ッツ Reader Authors): what ttu computes for these inputs. Do not
 * edit by hand; run the script again.
 */
internal object TtuFixture {
    const val JSON = """
{
 "updates": [
  {
   "timeDiff": 1,
   "characterDiff": 0,
   "at": 1790000000000,
   "after": {
    "title": "吾輩は猫である",
    "dateKey": "2026-09-20",
    "charactersRead": 0,
    "readingTime": 1,
    "minReadingSpeed": 0,
    "altMinReadingSpeed": 0,
    "lastReadingSpeed": 0,
    "maxReadingSpeed": 0,
    "lastStatisticModified": 1790000000000
   }
  },
  {
   "timeDiff": 1,
   "characterDiff": 0,
   "at": 1790000001000,
   "after": {
    "title": "吾輩は猫である",
    "dateKey": "2026-09-20",
    "charactersRead": 0,
    "readingTime": 2,
    "minReadingSpeed": 0,
    "altMinReadingSpeed": 0,
    "lastReadingSpeed": 0,
    "maxReadingSpeed": 0,
    "lastStatisticModified": 1790000001000
   }
  },
  {
   "timeDiff": 1,
   "characterDiff": 420,
   "at": 1790000002000,
   "after": {
    "title": "吾輩は猫である",
    "dateKey": "2026-09-20",
    "charactersRead": 420,
    "readingTime": 3,
    "minReadingSpeed": 504000,
    "altMinReadingSpeed": 504000,
    "lastReadingSpeed": 504000,
    "maxReadingSpeed": 504000,
    "lastStatisticModified": 1790000002000
   }
  },
  {
   "timeDiff": 1,
   "characterDiff": 0,
   "at": 1790000003000,
   "after": {
    "title": "吾輩は猫である",
    "dateKey": "2026-09-20",
    "charactersRead": 420,
    "readingTime": 4,
    "minReadingSpeed": 378000,
    "altMinReadingSpeed": 504000,
    "lastReadingSpeed": 378000,
    "maxReadingSpeed": 504000,
    "lastStatisticModified": 1790000003000
   }
  },
  {
   "timeDiff": 1,
   "characterDiff": 0,
   "at": 1790000004000,
   "after": {
    "title": "吾輩は猫である",
    "dateKey": "2026-09-20",
    "charactersRead": 420,
    "readingTime": 5,
    "minReadingSpeed": 302400,
    "altMinReadingSpeed": 504000,
    "lastReadingSpeed": 302400,
    "maxReadingSpeed": 504000,
    "lastStatisticModified": 1790000004000
   }
  },
  {
   "timeDiff": 1,
   "characterDiff": 0,
   "at": 1790000005000,
   "after": {
    "title": "吾輩は猫である",
    "dateKey": "2026-09-20",
    "charactersRead": 420,
    "readingTime": 6,
    "minReadingSpeed": 252000,
    "altMinReadingSpeed": 504000,
    "lastReadingSpeed": 252000,
    "maxReadingSpeed": 504000,
    "lastStatisticModified": 1790000005000
   }
  },
  {
   "timeDiff": 1,
   "characterDiff": 380,
   "at": 1790000006000,
   "after": {
    "title": "吾輩は猫である",
    "dateKey": "2026-09-20",
    "charactersRead": 800,
    "readingTime": 7,
    "minReadingSpeed": 252000,
    "altMinReadingSpeed": 411429,
    "lastReadingSpeed": 411429,
    "maxReadingSpeed": 504000,
    "lastStatisticModified": 1790000006000
   }
  },
  {
   "timeDiff": 1,
   "characterDiff": 0,
   "at": 1790000007000,
   "after": {
    "title": "吾輩は猫である",
    "dateKey": "2026-09-20",
    "charactersRead": 800,
    "readingTime": 8,
    "minReadingSpeed": 252000,
    "altMinReadingSpeed": 411429,
    "lastReadingSpeed": 360000,
    "maxReadingSpeed": 504000,
    "lastStatisticModified": 1790000007000
   }
  },
  {
   "timeDiff": 2,
   "characterDiff": 0,
   "at": 1790000008000,
   "after": {
    "title": "吾輩は猫である",
    "dateKey": "2026-09-20",
    "charactersRead": 800,
    "readingTime": 10,
    "minReadingSpeed": 252000,
    "altMinReadingSpeed": 411429,
    "lastReadingSpeed": 288000,
    "maxReadingSpeed": 504000,
    "lastStatisticModified": 1790000008000
   }
  },
  {
   "timeDiff": 1,
   "characterDiff": 510,
   "at": 1790000009000,
   "after": {
    "title": "吾輩は猫である",
    "dateKey": "2026-09-20",
    "charactersRead": 1310,
    "readingTime": 11,
    "minReadingSpeed": 252000,
    "altMinReadingSpeed": 411429,
    "lastReadingSpeed": 428728,
    "maxReadingSpeed": 504000,
    "lastStatisticModified": 1790000009000
   }
  },
  {
   "timeDiff": 1,
   "characterDiff": 0,
   "at": 1790000010000,
   "after": {
    "title": "吾輩は猫である",
    "dateKey": "2026-09-20",
    "charactersRead": 1310,
    "readingTime": 12,
    "minReadingSpeed": 252000,
    "altMinReadingSpeed": 411429,
    "lastReadingSpeed": 393000,
    "maxReadingSpeed": 504000,
    "lastStatisticModified": 1790000010000
   }
  },
  {
   "timeDiff": -300,
   "characterDiff": 0,
   "at": 1790000011000,
   "after": {
    "title": "吾輩は猫である",
    "dateKey": "2026-09-20",
    "charactersRead": 1310,
    "readingTime": 0,
    "minReadingSpeed": 0,
    "altMinReadingSpeed": 411429,
    "lastReadingSpeed": 0,
    "maxReadingSpeed": 504000,
    "lastStatisticModified": 1790000011000
   }
  },
  {
   "timeDiff": 1,
   "characterDiff": 0,
   "at": 1790000012000,
   "after": {
    "title": "吾輩は猫である",
    "dateKey": "2026-09-20",
    "charactersRead": 1310,
    "readingTime": 1,
    "minReadingSpeed": 4716000,
    "altMinReadingSpeed": 411429,
    "lastReadingSpeed": 4716000,
    "maxReadingSpeed": 4716000,
    "lastStatisticModified": 1790000012000
   }
  },
  {
   "timeDiff": 0,
   "characterDiff": 350,
   "at": 1790000013000,
   "after": {
    "title": "吾輩は猫である",
    "dateKey": "2026-09-20",
    "charactersRead": 1660,
    "readingTime": 1,
    "minReadingSpeed": 4716000,
    "altMinReadingSpeed": 411429,
    "lastReadingSpeed": 5976000,
    "maxReadingSpeed": 5976000,
    "lastStatisticModified": 1790000013000
   }
  },
  {
   "timeDiff": 1,
   "characterDiff": 0,
   "at": 1790000014000,
   "after": {
    "title": "吾輩は猫である",
    "dateKey": "2026-09-20",
    "charactersRead": 1660,
    "readingTime": 2,
    "minReadingSpeed": 2988000,
    "altMinReadingSpeed": 411429,
    "lastReadingSpeed": 2988000,
    "maxReadingSpeed": 5976000,
    "lastStatisticModified": 1790000014000
   }
  },
  {
   "timeDiff": 1,
   "characterDiff": 1,
   "at": 1790000015000,
   "after": {
    "title": "吾輩は猫である",
    "dateKey": "2026-09-20",
    "charactersRead": 1661,
    "readingTime": 3,
    "minReadingSpeed": 1993200,
    "altMinReadingSpeed": 411429,
    "lastReadingSpeed": 1993200,
    "maxReadingSpeed": 5976000,
    "lastStatisticModified": 1790000015000
   }
  },
  {
   "timeDiff": -5000,
   "characterDiff": 0,
   "at": 1790000016000,
   "after": {
    "title": "吾輩は猫である",
    "dateKey": "2026-09-20",
    "charactersRead": 1661,
    "readingTime": 0,
    "minReadingSpeed": 0,
    "altMinReadingSpeed": 411429,
    "lastReadingSpeed": 0,
    "maxReadingSpeed": 5976000,
    "lastStatisticModified": 1790000016000
   }
  },
  {
   "timeDiff": 1,
   "characterDiff": 0,
   "at": 1790000017000,
   "after": {
    "title": "吾輩は猫である",
    "dateKey": "2026-09-20",
    "charactersRead": 1661,
    "readingTime": 1,
    "minReadingSpeed": 5979600,
    "altMinReadingSpeed": 411429,
    "lastReadingSpeed": 5979600,
    "maxReadingSpeed": 5979600,
    "lastStatisticModified": 1790000017000
   }
  },
  {
   "timeDiff": 3,
   "characterDiff": 90,
   "at": 1790000018000,
   "after": {
    "title": "吾輩は猫である",
    "dateKey": "2026-09-20",
    "charactersRead": 1751,
    "readingTime": 4,
    "minReadingSpeed": 1575900,
    "altMinReadingSpeed": 411429,
    "lastReadingSpeed": 1575900,
    "maxReadingSpeed": 5979600,
    "lastStatisticModified": 1790000018000
   }
  },
  {
   "timeDiff": 1,
   "characterDiff": 0,
   "at": 1790000019000,
   "after": {
    "title": "吾輩は猫である",
    "dateKey": "2026-09-20",
    "charactersRead": 1751,
    "readingTime": 5,
    "minReadingSpeed": 1260720,
    "altMinReadingSpeed": 411429,
    "lastReadingSpeed": 1260720,
    "maxReadingSpeed": 5979600,
    "lastStatisticModified": 1790000019000
   }
  }
 ],
 "fileNames": [
  {
   "statistics": [
    {
     "title": "吾輩は猫である",
     "dateKey": "2026-09-22",
     "charactersRead": 12000,
     "readingTime": 3600,
     "minReadingSpeed": 9000,
     "altMinReadingSpeed": 9500,
     "lastReadingSpeed": 12000,
     "maxReadingSpeed": 15000,
     "lastStatisticModified": 1790000123456
    },
    {
     "title": "吾輩は猫である",
     "dateKey": "2026-09-20",
     "charactersRead": 3500,
     "readingTime": 1800,
     "minReadingSpeed": 5000,
     "altMinReadingSpeed": 6000,
     "lastReadingSpeed": 7000,
     "maxReadingSpeed": 9000,
     "lastStatisticModified": 1790000000000
    },
    {
     "title": "吾輩は猫である",
     "dateKey": "2026-09-21",
     "charactersRead": 0,
     "readingTime": 0,
     "minReadingSpeed": 0,
     "altMinReadingSpeed": 0,
     "lastReadingSpeed": 0,
     "maxReadingSpeed": 0,
     "lastStatisticModified": 1790000050000
    },
    {
     "title": "吾輩は猫である",
     "dateKey": "2026-09-23",
     "charactersRead": 777,
     "readingTime": 61,
     "minReadingSpeed": 40000,
     "altMinReadingSpeed": 45000,
     "lastReadingSpeed": 45856,
     "maxReadingSpeed": 50000,
     "lastStatisticModified": 1790000100000
    }
   ],
   "lastStatisticModified": 1790000123456,
   "fileName": "statistics_1_6_1790000123456_16277_5461_40000_45000_10731_45856_1821_3045_5426_9073_10727_10727_na.json",
   "sortedFileName": "statistics_1_6_1790000123456_16277_5461_9000_9500_10731_45856_1821_3045_5426_9073_10727_10727_na.json",
   "content": "[{\"title\":\"吾輩は猫である\",\"dateKey\":\"2026-09-20\",\"charactersRead\":3500,\"readingTime\":1800,\"minReadingSpeed\":5000,\"altMinReadingSpeed\":6000,\"lastReadingSpeed\":7000,\"maxReadingSpeed\":9000,\"lastStatisticModified\":1790000000000},{\"title\":\"吾輩は猫である\",\"dateKey\":\"2026-09-21\",\"charactersRead\":0,\"readingTime\":0,\"minReadingSpeed\":0,\"altMinReadingSpeed\":0,\"lastReadingSpeed\":0,\"maxReadingSpeed\":0,\"lastStatisticModified\":1790000050000},{\"title\":\"吾輩は猫である\",\"dateKey\":\"2026-09-22\",\"charactersRead\":12000,\"readingTime\":3600,\"minReadingSpeed\":9000,\"altMinReadingSpeed\":9500,\"lastReadingSpeed\":12000,\"maxReadingSpeed\":15000,\"lastStatisticModified\":1790000123456},{\"title\":\"吾輩は猫である\",\"dateKey\":\"2026-09-23\",\"charactersRead\":777,\"readingTime\":61,\"minReadingSpeed\":40000,\"altMinReadingSpeed\":45000,\"lastReadingSpeed\":45856,\"maxReadingSpeed\":50000,\"lastStatisticModified\":1790000100000}]"
  },
  {
   "statistics": [
    {
     "title": "Re:ゼロから始める異世界生活",
     "dateKey": "2026-09-24",
     "charactersRead": 5000,
     "readingTime": 1000,
     "minReadingSpeed": 17000,
     "altMinReadingSpeed": 17500,
     "lastReadingSpeed": 18000,
     "maxReadingSpeed": 19000,
     "lastStatisticModified": 1790000999999,
     "completedBook": 1,
     "completedData": {
      "dateKey": "2026-09-26",
      "charactersRead": 9000,
      "readingTime": 2000,
      "minReadingSpeed": 1,
      "altMinReadingSpeed": 2,
      "lastReadingSpeed": 3,
      "maxReadingSpeed": 4
     }
    },
    {
     "title": "Re:ゼロから始める異世界生活",
     "dateKey": "2026-09-23",
     "charactersRead": 4000,
     "readingTime": 1000,
     "minReadingSpeed": 14000,
     "altMinReadingSpeed": 14400,
     "lastReadingSpeed": 14400,
     "maxReadingSpeed": 16000,
     "lastStatisticModified": 1790000900000,
     "completedBook": 1,
     "completedData": {
      "dateKey": "2026-09-25",
      "charactersRead": 4000,
      "readingTime": 1000,
      "minReadingSpeed": 1,
      "altMinReadingSpeed": 2,
      "lastReadingSpeed": 3,
      "maxReadingSpeed": 4
     }
    }
   ],
   "lastStatisticModified": 1790000999999,
   "fileName": "statistics_1_6_1790000999999_9000_2000_14000_14400_16200_18000_1000_1000_4500_4500_16200_16200_2026-09-25.json",
   "sortedFileName": "statistics_1_6_1790000999999_9000_2000_14000_14400_16200_18000_1000_1000_4500_4500_16200_16200_2026-09-26.json",
   "content": "[{\"title\":\"Re:ゼロから始める異世界生活\",\"dateKey\":\"2026-09-23\",\"charactersRead\":4000,\"readingTime\":1000,\"minReadingSpeed\":14000,\"altMinReadingSpeed\":14400,\"lastReadingSpeed\":14400,\"maxReadingSpeed\":16000,\"lastStatisticModified\":1790000900000,\"completedBook\":1,\"completedData\":{\"dateKey\":\"2026-09-25\",\"charactersRead\":4000,\"readingTime\":1000,\"minReadingSpeed\":1,\"altMinReadingSpeed\":2,\"lastReadingSpeed\":3,\"maxReadingSpeed\":4}},{\"title\":\"Re:ゼロから始める異世界生活\",\"dateKey\":\"2026-09-24\",\"charactersRead\":5000,\"readingTime\":1000,\"minReadingSpeed\":17000,\"altMinReadingSpeed\":17500,\"lastReadingSpeed\":18000,\"maxReadingSpeed\":19000,\"lastStatisticModified\":1790000999999,\"completedBook\":1,\"completedData\":{\"dateKey\":\"2026-09-26\",\"charactersRead\":9000,\"readingTime\":2000,\"minReadingSpeed\":1,\"altMinReadingSpeed\":2,\"lastReadingSpeed\":3,\"maxReadingSpeed\":4}}]"
  },
  {
   "statistics": [],
   "lastStatisticModified": 1,
   "fileName": "statistics_1_6_1_0_0_0_0_0_0_0_0_0_0_0_0_na.json",
   "sortedFileName": "statistics_1_6_1_0_0_0_0_0_0_0_0_0_0_0_0_na.json",
   "content": "[]"
  }
 ],
 "sanitized": [
  {
   "title": "吾輩は猫である",
   "sanitized": "吾輩は猫である"
  },
  {
   "title": "Re:ゼロから始める異世界生活",
   "sanitized": "Re%3Aゼロから始める異世界生活"
  },
  {
   "title": "a/b?c<d>e\\f:g*h|i%j\"k",
   "sanitized": "a%2Fb%3Fc%3Cd%3Ee%5Cf%3Ag~ttu-star~h%7Ci%25j%22k"
  },
  {
   "title": "ends with space ",
   "sanitized": "ends with space~ttu-spc~"
  },
  {
   "title": "two spaces  ",
   "sanitized": "two spaces ~ttu-spc~"
  },
  {
   "title": "ends with dot.",
   "sanitized": "ends with dot~ttu-dend~"
  },
  {
   "title": "dots..",
   "sanitized": "dots.~ttu-dend~"
  },
  {
   "title": "***",
   "sanitized": "~ttu-star~~ttu-star~~ttu-star~"
  },
  {
   "title": "plain",
   "sanitized": "plain"
  }
 ]
}
"""
}
